### ISSUE TITLE
Restaurant Inspections Data And Violations

### ISSUE THREAD

**Issue by interglobalmedia** [BetaNYC/citygram-services-nyc#10]
https://data.cityofnewyork.us/Health/DOHMH-New-York-City-Restaurant-Inspection-Results/xx67-kt59?

Is the link to the open data regarding restaurants inspections and violations. - Maria

**Comment by fma2** [comment]
@interglobalmedia @dirkkelly Good news - I hacked at this the past few days and was able to get a data feed going!

Here's the Citygram connector that makes the feed: https://github.com/BetaNYC/citygram-services-nyc/blob/restaurant-inspection/lib/spy_glass/registry/nyc-restaurant-inspection-results.rb

I also deployed it to https://staging-citygram-services-nyc.herokuapp.com/.  Select "/nyc-restaurant-inspection-results" to view the data.  It takes about a minute to load the feed when you select the link; I'm considering ways to optimize this.  However, when I tried the feed locally on Citygram, it didn't seem to cause much of a difference in terms of speed. 

The primary fix I need to make involves how each event is mapped.  A single restaurant can have more than one inspection report.  For email/text notifications, this is fine--as inspections will show up in a list and will thus show all of the inspection reports for a single restaurant. When Citygram maps this, however, Mapbox places all of these inspections on the same longitude-latitude point, so you can't really see all of them on the map.

**Comment by interglobalmedia** [comment]
Pretty cool Farheen!

**Comment by dirkkelly** [comment]
@fma2 great work! We're going work to make this live
