### ISSUE TITLE
Set up RSVP / Save the date event

### ISSUE THREAD

**Issue by noneck** [BetaNYC/citygram-services-nyc#16]

**Comment by noneck** [comment]
# Let us improve CityGram.NYC - JOIN US FOR CITYGRAM SATURDAY!

On Sat, Oct 24, from Noon till 7:00 pm, we're going to improve NYC's CityGram notifications!

CityGram.NYC is a geographic notification platform designed to work with open government data. It allows residents to designate area(s) of a city they are interested in and subscribe to one or more topics.  For this weekend, we're going to subdivide NYC's 311 data feeds and teach you how to build new notification feeds. 

We are looking for 10 - 15 skilled civic hackers who want to spend a Saturday afternoon learning how to maintain CityGram.NYC and build up its data resources. Our long term goal is build up a dedicated, volunteer support team that can support CityGram. 

## Things you will do on CityGram Saturday
1. Write up a user persona and user story outlining why someone would access this CityGram feed.
2. Define the specific data feed
3. Select an [noun project icon](https://thenounproject.com) for your data feed.
4. Build a CityGram services script.
5. Submit a pull request to.

## Things you need to do before arriving.
1. Some programing experience, i.e. you need to know how scripts works.
2. Comfortable with GitHub pull requests.
3. Join [BetaNYC's slack channel](http://slack.beta.nyc) and hop into #citygram. 
4. Review NYC 311's data and think about what you type of data you or your friends would want to use.
5. Join [talk.beta.nyc/CityGram.NYC](https://talk.beta.nyc/c/working-groups/citygram) and [start watching the category](https://github.com/discourse/discourse/wiki/Basic-Usage-Guide#category-notifications).
6. Check out [NYC 311 Categories with Complaint Types](https://docs.google.com/document/d/1ON143VSMC9bDExlWFV7sG-Ly29949JAg5QPLkr2DGpk/edit?usp=sharing)

## Date and Location

Date: Saturday, 24 Oct 2015
Location: TBD

## RSVP

Comment on this issue with your first & last name, email address, & super power.

#19 <-- this is where people will rsvp

**Comment by noneck** [comment]
@dirkkelly can you give me some quick feedback?

Also, people will RSVP to a new issue.

**Comment by dirkkelly** [comment]
@noneck looks great, added @fma2's work on the 311 data sets, RSVP issue lgtm also

**Comment by noneck** [comment]
LGTM?

##

**Comment by dirkkelly** [comment]
@noneck sorry, looks good to me

**Comment by noneck** [comment]
Cool! Check out #19 for RSVPS.
