### ISSUE TITLE
JOIN US FOR CITYGRAM SATURDAY - 24 Oct!

### ISSUE THREAD

**Issue by noneck** [BetaNYC/citygram-services-nyc#19]
# Join Us For [CityGram.NYC](https://www.citygram.nyc/) Saturday
## Help improve notifications for NYC 311 Open Data

On Sat, Oct 24, from **Noon till 7:00 pm**, we're going to improve NYC's CityGram notifications!

CityGram.NYC is a geographic notification platform designed to work with open government data. It allows residents to designate area(s) of a city they are interested in and subscribe to one or more topics. For this weekend, we're going to subdivide NYC's 311 data feeds and teach you how to build new notification feeds. 

We are looking for 10 - 15 skilled civic hackers who want to spend a Saturday afternoon learning how to maintain CityGram.NYC and build up its data resources. Our long term goal is build up a dedicated, volunteer support team that can support CityGram. 

**To attend this event, leave a comment on this github issue with your name, email address, and superpower.**

---
### Why we're doing it
1. We want to make Citygram more relevant and useful for all New Yorkers
2. We want to teach people how to use the open data portals. More users, means more support
3. We want to break up the 311 Notifications into more useful feeds, school closures, potholes, streetlights, etc.
4. We want to show people they can be a part of open source development without any long term commitments
5. We also want to show those who are interested in longer term projects, how rewarding this can be
### Who will be there to help out

We have a dedicated team of Citygram maintainers who love teaching people about open data.
- Noel (@noneck) _Data and Society Fellow and BetaNYC Organizer_
- Dirk (@dirkkelly) _Maintainer of Citygram Code, former Codenow teacher, former Pivot_
- Farheen (@fma2) _Maintainer of Citygram Data, Educator, Technologist_
- John (@excepttheweasel) _Regular contributor to Citygram, former Codenow teacher, former Pivot_
### Why would you want to do this:
1. You want to learn about the open data and improve NYC's open data.
2. You're interested in building software that helps people using open data.
3. You'd like to meet people who've built software from open data, and learn from them.
### Things we'll be doing on CityGram Saturday
1. Write a user story outlining why someone would access this CityGram feed.
2. Discover the correct data feed by working with the data team
3. Select an [noun project icon](https://thenounproject.com) for your data feed.
4. Build a CityGram services script.
5. Submit a pull request to CityGram's repo.

[![](https://cloud.githubusercontent.com/assets/81055/10557237/a6082104-7471-11e5-9244-78a53d7d3f74.png)](https://github.com/BetaNYC/citygram-services-nyc/pull/29)

> [Pothole only data feed](https://github.com/BetaNYC/citygram-services-nyc/pull/29/files#diff-0e2de37a532ba65bec69af5e2edf81b3R12), using a simple condition on existing 311 data

[<img width="412" alt="screen shot 2015-10-17 at 1 56 56 am" src="https://cloud.githubusercontent.com/assets/81055/10557261/781cb948-7472-11e5-860d-14038d464565.png">](https://github.com/BetaNYC/citygram-services-nyc/pull/29/files#diff-0e2de37a532ba65bec69af5e2edf81b3R12)
### Things you know/need to do before arriving.
1. Some programing experience (if you know what a variable is, you're there!). `x = 123`
2. Comfortable with GitHub pull requests.
3. Join [BetaNYC's slack channel](http://slack.beta.nyc) and hop into #citygram. 
4. Review NYC 311's data and think about what you type of data you or your friends would want to use.
5. Join [talk.beta.nyc/CityGram.NYC](https://talk.beta.nyc/c/working-groups/citygram) and [start watching the category](https://github.com/discourse/discourse/wiki/Basic-Usage-Guide#category-notifications).
### Useful Resources
1. [Installing Citygram on a development machine](https://github.com/BetaNYC/citygram-nyc/#installation-and-configuration)
2. [NYC 311 Categories with Complaint Types](https://docs.google.com/document/d/1ON143VSMC9bDExlWFV7sG-Ly29949JAg5QPLkr2DGpk/edit?usp=sharing) or this is a roll up of the [Complaint Types on the City's open data portal](https://docs.google.com/spreadsheets/d/1Vvwlyy0mmALpG1JH04wZHes6pNzxiG_-WT4BtyfD5m0/edit?usp=sharing)
3. [Building a Citygram Adapter](https://github.com/codeforamerica/citygram/wiki/Getting-Started-with-Citygram)
### Date and Location

Date: Saturday, 24 Oct 2015
Location: Data & Society; [36 West 20th Street, 11th Floor, New York NY](https://goo.gl/maps/Lf3L2DgPKX22)

**Schedule**
Noon - Doors open (We'll have coffee and juice)
Noon:30 - Event starts
5 pm - Dinnerish
7 pm - Clean up

---
### RSVP

Comment on this issue with your first & last name, email address, & super power.

Confirmed attendants
1. @noneck
2. @dirkkelly
3. @fma2
4. @excepttheweasel 
5. @mashcode (Maybe)
6. @fattyduck 
7. @tomca32 
8. @seanluciotolentino 
9. @karissa 
10. @gfleetwood
11. @mikedillion 
12. @benmoss 
13. @SokhnaVor 
14. @rayrshah

**Comment by j16r** [comment]
I'll be there.

John Barker, jebarker@gmail.com, hitting the snooze button.

**Comment by noneck** [comment]
@excepttheweasel good! cause you're going to help co-host the event!!! ;-)

**Comment by dirkkelly** [comment]
Dirk Kelly, citygram@dirkkelly.com, gramming cities

**Comment by fma2** [comment]
Farheen Malik, farheen.m.malik@gmail.com, listening to podcasts

**Comment by noneck** [comment]
@fma2 happy to have you co-host the event! It is the CityGram jamband!

**Comment by mashcode** [comment]
Hi all, Is virtual participation ok in tandem? Coincidently I just yesterday spoke with a director from GrowNYC Grow to Learn about utilizing this. Communication among the various Greenies is still wedded to email so citygram could at least provide a shared platform . They have data but...it'll need some structure.

marc@marcshifflett.com / plum tarts

**Comment by mashcode** [comment]
Oops my bad...didn't see the 311 hook. Sorry. You're welcome to my garden green space and rooster data. I can upload to data.beta

**Comment by noneck** [comment]
@mashcode We really want in person attendance. In the future, we imagine virtual participation.

**Comment by fattyduck** [comment]
Greetings everyone, been interested in joining this meetup for a long time. I am sure there is a lot to learn and much thanks to host for the opportunity.

Dison Ruan
dison.ruan@yahoo.com

**Comment by tomca32** [comment]
I'd like to hop in.

Tomislav Pesut
t@tomislav.io
Doing no work, getting the credit and getting away with it

**Comment by noneck** [comment]
Is that your superpower?

I hope you're coming to get some work done.

**Comment by tomca32** [comment]
That's definitely my superpower.

Just kidding though, I'm actually going to get some work done.

**Comment by seanluciotolentino** [comment]
Lucio, seanluciotolentino@gmail.com, waking up early and not being crabby about it

**Comment by okdistribute** [comment]
Woohoo! sounds fun

**Comment by gfleetwood** [comment]
Hello,

Name: Gordon Fleetwood
Email: gordonfleetwood@yahoo.com
Superpower: Stoicism

**Comment by mikedillion** [comment]
Name: Mike Dillion
Email: mike.dillion@gmail.com

**Comment by benmoss** [comment]
Ben Moss
citygramrulez@mossity.com
Ability to destroy peoples entire notion of self-worth with a single eye roll

**Comment by SokhnaVor** [comment]
Sokhna Vor 
sokhna.sea@gmail.com
Ability to strategize and reach goals in seconds.

**Comment by noneck** [comment]
@dirkkelly, @fma2, @excepttheweasel, @mashcode, @fattyduck, @tomca32, @seanluciotolentino, @karissa, @gfleetwood @mikedillion @benmoss

You should have an email in your inbox. Please read it b/c it contains important details about this weekend's event.

This is a copy of the email, but it doesn't contain how to get into the building.

Tomorrow at Noon, we're meeting at **Data & Society**. Please bring a laptop, power supply, and be there at noon. 

Data & Society is located at 36 West 20th Street, 11th Floor, New York NY 10011

We will start off with a bit of collective training. We'll focus on the day's objectives and host a conversation around NYC 311. Then, we will break off into small groups / pair-programming to develop scripts.

@dirkkelly has created an example of the work we will be producing. < https://github.com/BetaNYC/citygram-services-nyc/pull/29 >

If you have any issue getting into the building, call me at 937.218.2422.

PS - We'll have coffee, but come fed. Around 4, we'll order dinner.
- Noel

**Comment by dirkkelly** [comment]
Cheers @noneck, looking forward to seeing you all tomorrow.

**Comment by json2d** [comment]
Name: Jason Yung
Email: json.yung@gmail.com
Superpower: Efficenc

**Comment by MasterXyu** [comment]
Andrey Scherbinin, nycsqllab@gmail.com
Never late lol
