### ISSUE TITLE
User Tested Invitation

### ISSUE THREAD

**Issue by dirkkelly** [BetaNYC/citygram-services-nyc#20]
# Join Us For [Citygram](https://www.citygram.nyc/) Saturday
## Saturday October 24th 2015, Location TBD

Let's improve how New Yorkers learn about what's going on in their city with Citygram, a free, open-source, open-data portal into New York City data.
### Why would you want to do this
1. You're interested in making society better
2. You want to learn about the open data available for NYC
3. You're interested in building software that helps people using open data
4. You'd like to meet people who've built software from open data, and learn from them
5. You'd like free dinner (it's catered!)
### Why we're doing it
1. We want to make Citygram more relevant and useful for all New Yorkers
2. We want to teach people how to use the open data portals. More users, means more support
3. We want to break up the 311 Notifications into more useful feeds, school closures, potholes, streetlights, etc.
4. We want to show people they can be a part of open source development without any long term commitments
5. We also want to show those who are interested in longer term projects, how rewarding this can be
### Who will be there to help out

We have a really dedicated team of Citygram maintainers who love teaching people about open data
- Noel (@noneck)  
  _Organizer_
- Dirk (@dirkkelly)  
  _Maintainer of Citygram Code, former Codenow teacher, former Pivot_
- Farheen (@fma2)  
  _Maintainer of Citygram Data, Educator, Technologist_
- John (@excepttheweasel)  
  _Regular contributor to Citygram, former Codenow teacher, former Pivot_
### Things you know/need to do before arriving.
1. Some programing experience (if you know what a variable is, you're there!). `x = 123`
2. Comfortable with GitHub pull requests.
3. Join [BetaNYC's slack channel](http://slack.beta.nyc) and hop into #citygram. 
4. Review NYC 311's data and think about what you type of data you or your friends would want to use.
5. Join [talk.beta.nyc/CityGram.NYC](https://talk.beta.nyc/c/working-groups/citygram) and [start watching the category](https://github.com/discourse/discourse/wiki/Basic-Usage-Guide#category-notifications).
### Things we'll be doing on CityGram Saturday
1. Write a user story outlining why someone would access this CityGram feed.
   > I'm a middle schooler from East Flatbush who wants to know when school is closed
2. Discover the correct data feed by working with the data team
3. Select an [noun project icon](https://thenounproject.com) for your data feed.
4. Build a CityGram services script.
5. Submit a pull request to CityGram's repo.
### Useful Resources
1. [Installing Citygram on a development machine](https://github.com/BetaNYC/citygram-nyc/#installation-and-configuration)
2. [NYC 311 Categories with Complaint Types](https://docs.google.com/document/d/1ON143VSMC9bDExlWFV7sG-Ly29949JAg5QPLkr2DGpk/edit?usp=sharing)
3. [Building a Citygram Adapter](https://github.com/codeforamerica/citygram/wiki/Getting-Started-with-Citygram)
### RSVP

Comment on this issue with your first & last name, email address, & super power.

**Comment by dirkkelly** [comment]
@noneck we updated the invitation after sitting with a friend who's on the level we're looking for. What do you think?

**Comment by noneck** [comment]
# Let us improve CityGram.NYC - JOIN US FOR CITYGRAM SATURDAY!

On Sat, Oct 24, from Noon till 7:00 pm, we're going to improve NYC's CityGram notifications!

CityGram.NYC is a geographic notification platform designed to work with open government data. It allows residents to designate area(s) of a city they are interested in and subscribe to one or more topics. For this weekend, we're going to subdivide NYC's 311 data feeds and teach you how to build new notification feeds. 

We are looking for 10 - 15 skilled civic hackers who want to spend a Saturday afternoon learning how to maintain CityGram.NYC and build up its data resources. Our long term goal is build up a dedicated, volunteer support team that can support CityGram. 

To attend this event, leave a comment on this github issue with your name, email address, and superpower (make a comment on #19)

### Why we're doing it
1. We want to make Citygram more relevant and useful for all New Yorkers
2. We want to teach people how to use the open data portals. More users, means more support
3. We want to break up the 311 Notifications into more useful feeds, school closures, potholes, streetlights, etc.
4. We want to show people they can be a part of open source development without any long term commitments
5. We also want to show those who are interested in longer term projects, how rewarding this can be

### Who will be there to help out

We have a dedicated team of Citygram maintainers who love teaching people about open data.
- Noel (@noneck) _Data and Society Fellow and BetaNYC Organizer_
- Dirk (@dirkkelly) _Maintainer of Citygram Code, former Codenow teacher, former Pivot_
- Farheen (@fma2) _Maintainer of Citygram Data, Educator, Technologist_
- John (@excepttheweasel) _Regular contributor to Citygram, former Codenow teacher, former Pivot_

### Why would you want to do this:
1. You want to learn about the open data and improve NYC's open data.
2. You're interested in building software that helps people using open data.
3. You'd like to meet people who've built software from open data, and learn from them.

### Things we'll be doing on CityGram Saturday
1. Write a user story outlining why someone would access this CityGram feed.
   > I'm a middle schooler from East Flatbush who wants to know when school is closed
2. Discover the correct data feed by working with the data team
3. Select an [noun project icon](https://thenounproject.com) for your data feed.
4. Build a CityGram services script.
5. Submit a pull request to CityGram's repo.

### Things you know/need to do before arriving.
1. Some programing experience (if you know what a variable is, you're there!). `x = 123`
2. Comfortable with GitHub pull requests.
3. Join [BetaNYC's slack channel](http://slack.beta.nyc) and hop into #citygram. 
4. Review NYC 311's data and think about what you type of data you or your friends would want to use.
5. Join [talk.beta.nyc/CityGram.NYC](https://talk.beta.nyc/c/working-groups/citygram) and [start watching the category](https://github.com/discourse/discourse/wiki/Basic-Usage-Guide#category-notifications).

### Useful Resources
1. [Installing Citygram on a development machine](https://github.com/BetaNYC/citygram-nyc/#installation-and-configuration)
2. [NYC 311 Categories with Complaint Types](https://docs.google.com/document/d/1ON143VSMC9bDExlWFV7sG-Ly29949JAg5QPLkr2DGpk/edit?usp=sharing)
3. [Building a Citygram Adapter](https://github.com/codeforamerica/citygram/wiki/Getting-Started-with-Citygram)

**Comment by dirkkelly** [comment]
The user found it pretty intimidating to read all that stuff about us without understanding what their commitment will be

**Comment by noneck** [comment]
@dirkkelly i put a shorter version on meetup to do some AB testing.... What do you thinK? 

http://www.meetup.com/betanyc/events/226031486/

**Comment by dirkkelly** [comment]
I reckon you've got some people signing up! Looking good thanks. I've got a pull request for potholes that I'm going to add to the Invite PR. Closing this.
